- name: Post Rollback
  hosts: localhost
  gather_facts: no
  roles:
    - role: post_rollback
      vars:
        checks:
          - "oc wait co --all --for='condition=Available=True' --timeout=60s"
          - "oc wait co --all --for='condition=Progressing=False' --timeout=60s"
          - "oc wait co --all --for='condition=Degraded=False' --timeout=60s"
          - "oc wait mcp --all --for='condition=UPDATED=True' --timeout=60s"
          - "oc wait mcp --all --for='condition=UPDATING=False' --timeout=60s"
          - "oc wait mcp --all --for='condition=DEGRADED=False' --timeout=60s"
        network_provider_config: ovnKubernetesConfig
        namespace: openshift-ovn-kubernetes
        expected_network_type: OpenShiftSDN
        verify_machine_config_timeout: 300
        clean_migration_timeout: 120
