---
- name: End-to-End Test for verify_machine_config Module (Real OpenShift)
  hosts: localhost
  gather_facts: no
  vars:
    verify_machine_config_timeout: 15
  tasks:

    - name: Run verify_machine_config module (Failure due to config mismatch)
      verify_machine_config:
        timeout: "{{ verify_machine_config_timeout }}"
        network_type: "OVNKubernetes"
      register: result_config_mismatch
      ignore_errors: yes

    - name: Debug module output (Config Mismatch)
      debug:
        var: result_config_mismatch

    - name: Assert failure due to config mismatch
      assert:
        that:
          - result_config_mismatch is failed
          - "'currentConfig' in result_config_mismatch.issues"
      when: result_config_mismatch is failed

    - name: Run verify_machine_config module (Failure due to node not ready)
      verify_machine_config:
        timeout: "{{ verify_machine_config_timeout }}"
        network_type: "OVNKubernetes"
      register: result_node_not_ready
      ignore_errors: yes

    - name: Debug module output (Node Not Ready)
      debug:
        var: result_node_not_ready

    - name: Assert failure due to node not being ready
      assert:
        that:
          - result_node_not_ready is failed
          - "'state' in result_node_not_ready.issues"
      when: result_node_not_ready is failed

    - name: Run verify_machine_config module (Failure due to missing ExecStart)
      verify_machine_config:
        timeout: "{{ verify_machine_config_timeout }}"
        network_type: "OVNKubernetes"
      register: result_execstart_missing
      ignore_errors: yes

    - name: Debug module output (Missing ExecStart) #TODO Fix the returns from module to fetch execstart so that we can test
      debug:
        var: result_execstart_missing

    - name: Assert failure due to missing ExecStart
      assert:
        that:
          - result_execstart_missing is failed
          - "'ExecStart' in result_execstart_missing.issues"
      when: result_execstart_missing is failed

    - name: Run verify_machine_config module (Success scenario)
      verify_machine_config:
        timeout: "{{ verify_machine_config_timeout }}"
        network_type: "OVNKubernetes"
      register: result_success

    - name: Debug module output (Success)
      debug:
        var: result_success

    - name: Assert success scenario
      assert:
        that:
          - result_success is success
          - result_success.msg == "All machine configurations are correct."
      when: result_success is success

