---
- name: E2E Test - Verify KUBECONFIG existence
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Execute custom module to check KUBECONFIG
      check_kubeconfig:
      register: kubeconfig_result

    - name: Debug Output
      debug:
        msg: "{{ kubeconfig_result }}"

    - name: Assert KUBECONFIG exists
      assert:
        that:
          - kubeconfig_result.kubeconfig_path is defined
          - kubeconfig_result.kubeconfig_path | length > 0
        fail_msg: "❌ KUBECONFIG is missing or invalid!"
        success_msg: "✅ KUBECONFIG is set correctly!"

    - name: Print KUBECONFIG Path
      debug:
        msg: "KUBECONFIG Path: {{ kubeconfig_result.kubeconfig_path }}"
      when: not kubeconfig_result.failed
