- name: End-to-End Test for wait_for_mco Module
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Start a dummy MachineConfig update (simulating an update)
      command: >
        oc patch mcp worker --type=merge --patch '{"spec": { "paused": true } }'
      changed_when: false

    - name: Wait for MCO to start applying changes
      wait_for_mco:
        timeout: 300  # Adjust timeout as needed
      register: mco_status

    - name: Print MCO status
      debug:
        msg: "{{ mco_status.msg }}"

    - name: Verify that MCO started updating
      assert:
        that:
          - "'Timeout' not in mco_status.msg"
        fail_msg: "MCO did not start updating within the timeout!"
        success_msg: "MCO started updating successfully!"

    - name: Unpause worker MachineConfigPool (clean-up)
      command: >
        oc patch mcp worker --type=merge --patch '{"spec": { "paused": false } }'
      changed_when: false
